author:
  name: "Athena Zhang"
  avatar: /assets/images/profile.jpg
  bio: "Northeastern '25"
  location: "Boston, MA"
  links:
    - label: "CV"
      icon: "fas fa-link"
      url: "/assets/docs/cv.pdf"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:Athenaruiyu.zhang@outlook.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/athena-zhang-49778a263/"
